In [1]:
import numpy as np

In [2]:
# 시그모이드 함수
def actf(x):
    print("x in actf=", x)
    return 1/(1+np.exp(-x))

In [3]:
# 시그모이드 함수의 미분치
def actf_deriv(x):
    return x*(1-x)

In [4]:
# 입력유닛의 개수, 은닉유닛의 개수, 출력유닛의 개수
inputs, hiddens, outputs = 2, 2, 1
learning_rate=0.2

In [5]:
# 훈련 샘플과 정답
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
T = np.array([[0], [1], [1], [0]])

In [6]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [7]:
W1 = np.array([[0.10, 0.20],
                 [0.30, 0.40]])
W2 = np.array([[0.50], [0.60]])
B1 = np.array([0.1, 0.2])
B2 = np.array([0.3])

In [8]:
W1

array([[0.1, 0.2],
       [0.3, 0.4]])

In [9]:
# 순방향 전파 계산
def predict(x):
    layer0 = x                   # 입력을 layer0에 대입한다.
    print("layer0=", layer0)
    Z1 = np.dot(layer0, W1)+B1   # 행렬의 곱을 계산한다.
    print("Z1=", Z1)
    layer1 = actf(Z1)            # 활성화 함수를 적용한다.
    print("layer1=", layer1, "\n")
    Z2 = np.dot(layer1, W2)+B2   # 행렬의 곱을 계산한다.
    print("Z2=", Z2)
    layer2 = actf(Z2)            # 활성화 함수를 적용한다.
    print("layer2=", layer2, "\n")
    return layer0, layer1, layer2

In [10]:
def test():
    for x, y in zip(X, T):
        x = np.reshape(x, (1, -1))    # x를 2차원 행렬로 만든다.입력은 2차원이어야 한다.
        layer0, layer1, layer2 = predict(x)
        print(x, y, layer2)

In [11]:
test()

layer0= [[0 0]]
Z1= [[0.1 0.2]]
x in actf= [[0.1 0.2]]
layer1= [[0.52497919 0.549834  ]] 

Z2= [[0.89238999]]
x in actf= [[0.89238999]]
layer2= [[0.70938314]] 

[[0 0]] [0] [[0.70938314]]
layer0= [[0 1]]
Z1= [[0.4 0.6]]
x in actf= [[0.4 0.6]]
layer1= [[0.59868766 0.64565631]] 

Z2= [[0.98673761]]
x in actf= [[0.98673761]]
layer2= [[0.72844306]] 

[[0 1]] [1] [[0.72844306]]
layer0= [[1 0]]
Z1= [[0.2 0.4]]
x in actf= [[0.2 0.4]]
layer1= [[0.549834   0.59868766]] 

Z2= [[0.93412959]]
x in actf= [[0.93412959]]
layer2= [[0.71791234]] 

[[1 0]] [1] [[0.71791234]]
layer0= [[1 1]]
Z1= [[0.5 0.8]]
x in actf= [[0.5 0.8]]
layer1= [[0.62245933 0.68997448]] 

Z2= [[1.02521435]]
x in actf= [[1.02521435]]
layer2= [[0.73598705]] 

[[1 1]] [0] [[0.73598705]]
